/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hawa1;
 import javax.swing.*;
public class App {
    
   public static void main(String[] args) {
        
      
       
            
               
  }
}
